ipAddress=127.0.0.1
appiumJSPath=C://Users//Lenovo//AppData//Roaming//npm//node_modules//appium//build//lib//main.js
appPath=D://ITI_Courses//Appium_mobile_automation_self_study//APKFiles//resources//General-Store.apk
deviceName=Zahranemulator
chromedriverExecutable=C://Users//Lenovo//Desktop//chromedriver//win64-145.0.7632.117//chromedriver-win64//chromedriver.exe
